# Generated by Django 2.2.24 on 2021-08-26 21:53

import core.utils
from django.conf import settings
import django.contrib.gis.db.models.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0016_add_resolved'),
    ]

    operations = [
        migrations.AddField(
            model_name='helprequest',
            name='user_id',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='historicalhelprequest',
            name='user_id',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='helprequest',
            name='added',
            field=models.DateTimeField(auto_now_add=True, db_index=True, null=True, verbose_name='Added'),
        ),
        migrations.AlterField(
            model_name='helprequest',
            name='address',
            field=models.CharField(help_text='Your address, city, neighborhood, references, or how to get there, to get help', max_length=400, null=True, verbose_name='Address'),
        ),
        migrations.AlterField(
            model_name='helprequest',
            name='location',
            field=django.contrib.gis.db.models.fields.PointField(help_text='<p style="margin-bottom:5px;font-size:10px;">Select your location so that people can find you, if you do not want to mark your home a good option may be the nearest police station or some other nearby public place.<br>If you have problems with this step <a href="#" class="is-link modal-button" data-target="#myModal" aria-haspopup="true">Check out this help</a></p><p id="div_direccion" style="font-size: 10px; margin-bottom: 5px;"></p>', srid=4326, verbose_name='Location'),
        ),
        migrations.AlterField(
            model_name='helprequest',
            name='message',
            field=models.TextField(db_index=True, help_text='Here you can tell in detail what you need, <b> the better you tell your situation the more likely they want to help you </b>', max_length=2000, null=True, verbose_name='Request Description'),
        ),
        migrations.AlterField(
            model_name='helprequest',
            name='name',
            field=models.CharField(max_length=200, verbose_name='Name and surname'),
        ),
        migrations.AlterField(
            model_name='helprequest',
            name='phone',
            field=models.CharField(max_length=30, verbose_name='Telephone contact'),
        ),
        migrations.AlterField(
            model_name='helprequest',
            name='picture',
            field=models.ImageField(blank=True, help_text='In case you want you can attach a photo related to your request. It is optional but it can help people better understand your situation.', null=True, upload_to=core.utils.rename_img, verbose_name='Photo'),
        ),
        migrations.AlterField(
            model_name='helprequest',
            name='title',
            field=models.CharField(db_index=True, help_text='Short description of what you need', max_length=200, verbose_name='Request title'),
        ),
        migrations.AlterField(
            model_name='historicalhelprequest',
            name='added',
            field=models.DateTimeField(blank=True, db_index=True, editable=False, null=True, verbose_name='Added'),
        ),
        migrations.AlterField(
            model_name='historicalhelprequest',
            name='address',
            field=models.CharField(help_text='Your address, city, neighborhood, references, or how to get there, to get help', max_length=400, null=True, verbose_name='Address'),
        ),
        migrations.AlterField(
            model_name='historicalhelprequest',
            name='location',
            field=django.contrib.gis.db.models.fields.PointField(help_text='<p style="margin-bottom:5px;font-size:10px;">Select your location so that people can find you, if you do not want to mark your home a good option may be the nearest police station or some other nearby public place.<br>If you have problems with this step <a href="#" class="is-link modal-button" data-target="#myModal" aria-haspopup="true">Check out this help</a></p><p id="div_direccion" style="font-size: 10px; margin-bottom: 5px;"></p>', srid=4326, verbose_name='Location'),
        ),
        migrations.AlterField(
            model_name='historicalhelprequest',
            name='message',
            field=models.TextField(db_index=True, help_text='Here you can tell in detail what you need, <b> the better you tell your situation the more likely they want to help you </b>', max_length=2000, null=True, verbose_name='Request Description'),
        ),
        migrations.AlterField(
            model_name='historicalhelprequest',
            name='name',
            field=models.CharField(max_length=200, verbose_name='Name and surname'),
        ),
        migrations.AlterField(
            model_name='historicalhelprequest',
            name='phone',
            field=models.CharField(max_length=30, verbose_name='Telephone contact'),
        ),
        migrations.AlterField(
            model_name='historicalhelprequest',
            name='picture',
            field=models.TextField(blank=True, help_text='In case you want you can attach a photo related to your request. It is optional but it can help people better understand your situation.', max_length=100, null=True, verbose_name='Photo'),
        ),
        migrations.AlterField(
            model_name='historicalhelprequest',
            name='title',
            field=models.CharField(db_index=True, help_text='Short description of what you need', max_length=200, verbose_name='Request title'),
        ),
        migrations.CreateModel(
            name='UserAux',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=120, unique=True)),
                ('email', models.EmailField(max_length=254)),
                ('password', models.CharField(max_length=120)),
                ('codigo', models.CharField(max_length=6)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
