# Generated by Django 2.2.21 on 2021-09-09 23:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0017_auto_20210826_1753'),
    ]

    operations = [
        migrations.AddField(
            model_name='helprequest',
            name='cant_disponible',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='historicalhelprequest',
            name='cant_disponible',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
