# Generated by Django 2.2.21 on 2021-09-09 23:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0018_auto_20210909_1913'),
    ]

    operations = [
        migrations.AddField(
            model_name='helprequest',
            name='precio',
            field=models.CharField(blank=True, default='', help_text='Precio por unidad de medida.', max_length=100, null=True, verbose_name='Precio'),
        ),
        migrations.AddField(
            model_name='historicalhelprequest',
            name='precio',
            field=models.CharField(blank=True, default='', help_text='Precio por unidad de medida.', max_length=100, null=True, verbose_name='Precio'),
        ),
    ]
