# Generated by Django 2.2.21 on 2021-09-09 23:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0020_auto_20210909_1918'),
    ]

    operations = [
        migrations.AddField(
            model_name='helprequest',
            name='buscar',
            field=models.BooleanField(blank=True, default=False, null=True, verbose_name='Debe venir a buscar'),
        ),
        migrations.AddField(
            model_name='helprequest',
            name='delivery',
            field=models.BooleanField(blank=True, default=False, null=True, verbose_name='Delivery disponible para entrega de producto'),
        ),
        migrations.AddField(
            model_name='historicalhelprequest',
            name='buscar',
            field=models.BooleanField(blank=True, default=False, null=True, verbose_name='Debe venir a buscar'),
        ),
        migrations.AddField(
            model_name='historicalhelprequest',
            name='delivery',
            field=models.BooleanField(blank=True, default=False, null=True, verbose_name='Delivery disponible para entrega de producto'),
        ),
    ]
