# Generated by Django 2.2.21 on 2021-09-09 23:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0021_auto_20210909_1919'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='helprequest',
            name='fecha_disponibilidad',
        ),
        migrations.RemoveField(
            model_name='historicalhelprequest',
            name='fecha_disponibilidad',
        ),
    ]
