# Generated by Django 2.2.21 on 2021-09-10 22:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0022_auto_20210909_1929'),
    ]

    operations = [
        migrations.AddField(
            model_name='helprequest',
            name='fecha_disponibilidad',
            field=models.DateField(default='2021-08-13'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='historicalhelprequest',
            name='fecha_disponibilidad',
            field=models.DateField(default='2021-08-13'),
            preserve_default=False,
        ),
    ]
