# Generated by Django 2.2.21 on 2021-09-10 22:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0023_auto_20210910_1823'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='helprequest',
            name='fecha_disponibilidad',
        ),
        migrations.RemoveField(
            model_name='historicalhelprequest',
            name='fecha_disponibilidad',
        ),
    ]
