# Generated by Django 2.2.21 on 2021-09-10 22:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0024_auto_20210910_1830'),
    ]

    operations = [
        migrations.AddField(
            model_name='helprequest',
            name='ano_dis',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='helprequest',
            name='dia_dis',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='helprequest',
            name='mes_dis',
            field=models.IntegerField(blank=True, choices=[('1', 'Enero'), ('2', 'Febrero'), ('3', 'Marzo'), ('4', 'Abril'), ('5', 'Mayo'), ('6', 'Junio'), ('7', 'Julio'), ('8', 'Agosto'), ('9', 'Septiembre'), ('10', 'Octubre'), ('11', 'Noviembre'), ('12', 'Diciembre')], null=True),
        ),
        migrations.AddField(
            model_name='historicalhelprequest',
            name='ano_dis',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='historicalhelprequest',
            name='dia_dis',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='historicalhelprequest',
            name='mes_dis',
            field=models.IntegerField(blank=True, choices=[('1', 'Enero'), ('2', 'Febrero'), ('3', 'Marzo'), ('4', 'Abril'), ('5', 'Mayo'), ('6', 'Junio'), ('7', 'Julio'), ('8', 'Agosto'), ('9', 'Septiembre'), ('10', 'Octubre'), ('11', 'Noviembre'), ('12', 'Diciembre')], null=True),
        ),
    ]
