# Generated by Django 2.2.21 on 2021-09-10 23:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0026_auto_20210910_1839'),
    ]

    operations = [
        migrations.AddField(
            model_name='helprequest',
            name='fecha',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='historicalhelprequest',
            name='fecha',
            field=models.DateField(blank=True, null=True),
        ),
    ]
