# Generated by Django 2.2.21 on 2021-09-10 23:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0027_auto_20210910_1908'),
    ]

    operations = [
        migrations.AlterField(
            model_name='helprequest',
            name='fecha',
            field=models.DateField(blank=True, null=True, verbose_name='Fecha de disponibilidad'),
        ),
        migrations.AlterField(
            model_name='historicalhelprequest',
            name='fecha',
            field=models.DateField(blank=True, null=True, verbose_name='Fecha de disponibilidad'),
        ),
    ]
