# Generated by Django 2.2.21 on 2021-09-10 23:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0028_auto_20210910_1912'),
    ]

    operations = [
        migrations.AddField(
            model_name='helprequest',
            name='cantidad_disponible',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Cantidad Disponible'),
        ),
        migrations.AddField(
            model_name='historicalhelprequest',
            name='cantidad_disponible',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Cantidad Disponible'),
        ),
        migrations.AlterField(
            model_name='helprequest',
            name='cant_disponible',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='Cantidad Disponible'),
        ),
        migrations.AlterField(
            model_name='historicalhelprequest',
            name='cant_disponible',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='Cantidad Disponible'),
        ),
    ]
