# Generated by Django 2.2.21 on 2021-09-14 19:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0029_auto_20210910_1937'),
    ]

    operations = [
        migrations.AddField(
            model_name='helprequest',
            name='unidad_medida',
            field=models.IntegerField(blank=True, choices=[('1', 'KILOGRAMOS'), ('2', 'LITROS'), ('3', 'UNIDAD'), ('4', 'DOCENA')], null=True, verbose_name='UNIDAD DE MEDIDA'),
        ),
        migrations.AddField(
            model_name='historicalhelprequest',
            name='unidad_medida',
            field=models.IntegerField(blank=True, choices=[('1', 'KILOGRAMOS'), ('2', 'LITROS'), ('3', 'UNIDAD'), ('4', 'DOCENA')], null=True, verbose_name='UNIDAD DE MEDIDA'),
        ),
    ]
