# Generated by Django 2.2.21 on 2021-09-14 19:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0030_auto_20210914_1540'),
    ]

    operations = [
        migrations.AlterField(
            model_name='helprequest',
            name='cant_disponible',
            field=models.IntegerField(blank=True, null=True, verbose_name='Cantidad Disponible'),
        ),
        migrations.AlterField(
            model_name='historicalhelprequest',
            name='cant_disponible',
            field=models.IntegerField(blank=True, null=True, verbose_name='Cantidad Disponible'),
        ),
    ]
