# Generated by Django 2.2.24 on 2021-09-22 20:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0034_auto_20210922_1608'),
    ]

    operations = [
        migrations.AlterField(
            model_name='helprequest',
            name='buscar',
            field=models.BooleanField(blank=True, default=True, null=True, verbose_name='Debe venir a buscar'),
        ),
        migrations.AlterField(
            model_name='helprequest',
            name='delivery',
            field=models.BooleanField(blank=True, default=True, null=True, verbose_name='Delivery disponible para entrega de producto'),
        ),
        migrations.AlterField(
            model_name='historicalhelprequest',
            name='buscar',
            field=models.BooleanField(blank=True, default=True, null=True, verbose_name='Debe venir a buscar'),
        ),
        migrations.AlterField(
            model_name='historicalhelprequest',
            name='delivery',
            field=models.BooleanField(blank=True, default=True, null=True, verbose_name='Delivery disponible para entrega de producto'),
        ),
    ]
