# Generated by Django 2.2.24 on 2021-09-23 18:41

import core.utils
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0035_auto_20210922_1617'),
    ]

    operations = [
        migrations.AlterField(
            model_name='helprequest',
            name='unidad_medida',
            field=models.CharField(blank=True, choices=[('KILOGRAMOS', 'KILOGRAMOS'), ('LITROS', 'LITROS'), ('UNIDAD', 'UNIDAD'), ('DOCENA', 'DOCENA')], max_length=20, null=True, verbose_name='Unidad de medida de la cantidad disponible'),
        ),
        migrations.AlterField(
            model_name='historicalhelprequest',
            name='unidad_medida',
            field=models.CharField(blank=True, choices=[('KILOGRAMOS', 'KILOGRAMOS'), ('LITROS', 'LITROS'), ('UNIDAD', 'UNIDAD'), ('DOCENA', 'DOCENA')], max_length=20, null=True, verbose_name='Unidad de medida de la cantidad disponible'),
        ),
        migrations.CreateModel(
            name='UserDatosExtras',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('foto', models.ImageField(blank=True, help_text='In case you want you can attach a photo related to your request. It is optional but it can help people better understand your situation.', null=True, upload_to=core.utils.rename_img, verbose_name='Foto')),
                ('upload', models.FileField(upload_to='uploads/')),
                ('telefono', models.CharField(blank=True, max_length=30, null=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
