# Generated by Django 2.2.24 on 2021-09-23 20:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0036_auto_20210923_1441'),
    ]

    operations = [
        migrations.AlterField(
            model_name='helprequest',
            name='message',
            field=models.CharField(db_index=True, help_text='Here you can tell in detail what you need, <b> the better you tell your situation the more likely they want to help you </b>', max_length=500, null=True, verbose_name='Request Description'),
        ),
        migrations.AlterField(
            model_name='historicalhelprequest',
            name='message',
            field=models.CharField(db_index=True, help_text='Here you can tell in detail what you need, <b> the better you tell your situation the more likely they want to help you </b>', max_length=500, null=True, verbose_name='Request Description'),
        ),
    ]
