# Generated by Django 2.2.21 on 2021-09-24 00:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0039_auto_20210923_2013'),
    ]

    operations = [
        migrations.AlterField(
            model_name='helprequest',
            name='message',
            field=models.CharField(db_index=True, max_length=200, null=True, verbose_name='nombre'),
        ),
        migrations.AlterField(
            model_name='historicalhelprequest',
            name='message',
            field=models.CharField(db_index=True, max_length=200, null=True, verbose_name='nombre'),
        ),
    ]
