# Generated by Django 2.2.21 on 2021-09-24 01:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0040_auto_20210923_2016'),
    ]

    operations = [
        migrations.AddField(
            model_name='helprequest',
            name='name2',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Nombre completo'),
        ),
        migrations.AddField(
            model_name='historicalhelprequest',
            name='name2',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Nombre completo'),
        ),
        migrations.AlterField(
            model_name='helprequest',
            name='message',
            field=models.CharField(db_index=True, max_length=200, null=True, verbose_name='detalleparabusqueda'),
        ),
        migrations.AlterField(
            model_name='historicalhelprequest',
            name='message',
            field=models.CharField(db_index=True, max_length=200, null=True, verbose_name='detalleparabusqueda'),
        ),
    ]
