# Generated by Django 2.2.21 on 2021-09-24 02:50

import core.utils
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0042_auto_20210923_2236'),
    ]

    operations = [
        migrations.AddField(
            model_name='useraux',
            name='apellido',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='useraux',
            name='foto',
            field=models.ImageField(blank=True, help_text='In case you want you can attach a photo related to your request. It is optional but it can help people better understand your situation.', null=True, upload_to=core.utils.rename_img, verbose_name='Foto'),
        ),
        migrations.AddField(
            model_name='useraux',
            name='nombre',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='useraux',
            name='upload',
            field=models.FileField(blank=True, null=True, upload_to='uploads/'),
        ),
    ]
