# Generated by Django 2.2.21 on 2021-09-24 03:58

import core.utils
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0044_auto_20210923_2330'),
    ]

    operations = [
        migrations.AlterField(
            model_name='useraux',
            name='upload',
            field=models.FileField(blank=True, null=True, upload_to=core.utils.rename_img2, verbose_name='Documento de algun gremio'),
        ),
    ]
