# Generated by Django 2.2.21 on 2021-09-24 04:04

import core.utils
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0045_auto_20210923_2358'),
    ]

    operations = [
        migrations.AlterField(
            model_name='useraux',
            name='foto',
            field=models.ImageField(blank=True, null=True, upload_to=core.utils.rename_img, verbose_name='Foto'),
        ),
        migrations.AlterField(
            model_name='useraux',
            name='upload',
            field=models.FileField(blank=True, null=True, upload_to=core.utils.rename_img, verbose_name='Documento de algun gremio'),
        ),
    ]
