# Generated by Django 2.2.21 on 2021-09-24 04:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0047_auto_20210924_0010'),
    ]

    operations = [
        migrations.AlterField(
            model_name='useraux',
            name='foto',
            field=models.ImageField(blank=True, null=True, upload_to='imagen_user', verbose_name='Foto'),
        ),
        migrations.AlterField(
            model_name='useraux',
            name='upload',
            field=models.FileField(blank=True, null=True, upload_to='imagen_user', verbose_name='Documento de algun gremio'),
        ),
    ]
