# Generated by Django 2.2.24 on 2021-09-24 17:51

import core.utils
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0050_auto_20210924_1127'),
    ]

    operations = [
        migrations.AlterField(
            model_name='useraux',
            name='foto',
            field=models.ImageField(blank=True, upload_to=core.utils.rename_img, verbose_name='Foto'),
        ),
    ]
