# Generated by Django 2.2.24 on 2021-09-24 17:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0051_auto_20210924_1351'),
    ]

    operations = [
        migrations.AlterField(
            model_name='useraux',
            name='foto',
            field=models.ImageField(blank=True, upload_to='audio/', verbose_name='Foto'),
        ),
        migrations.AlterField(
            model_name='useraux',
            name='upload',
            field=models.FileField(blank=True, upload_to='audio/', verbose_name='Documento de algun gremio'),
        ),
    ]
