# Generated by Django 2.2.24 on 2021-09-24 18:15

import core.utils
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0053_auto_20210924_1403'),
    ]

    operations = [
        migrations.AddField(
            model_name='useraux',
            name='picture',
            field=models.ImageField(blank=True, help_text='In case you want you can attach a photo related to your request. It is optional but it can help people better understand your situation.', null=True, upload_to=core.utils.rename_img, verbose_name='Photo'),
        ),
    ]
