# Generated by Django 2.2.24 on 2021-09-24 19:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0054_useraux_picture'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='useraux',
            name='picture',
        ),
    ]
