# Generated by Django 2.2.24 on 2021-10-01 14:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0055_remove_useraux_picture'),
    ]

    operations = [
        migrations.AddField(
            model_name='useraux',
            name='bandera_foto',
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
        migrations.AddField(
            model_name='useraux',
            name='bandera_upload',
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
    ]
