# Generated by Django 2.2.24 on 2021-10-01 19:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0056_auto_20211001_1044'),
    ]

    operations = [
        migrations.AlterField(
            model_name='useraux',
            name='codigo',
            field=models.CharField(blank=True, max_length=6, null=True),
        ),
        migrations.AlterField(
            model_name='useraux',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='useraux',
            name='password',
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
    ]
