# Generated by Django 2.2.24 on 2021-10-01 20:43

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0057_auto_20211001_1520'),
    ]

    operations = [
        migrations.AlterField(
            model_name='useraux',
            name='foto',
            field=models.ImageField(blank=True, null=True, upload_to='pedidos/', verbose_name='Foto'),
        ),
        migrations.AlterField(
            model_name='useraux',
            name='upload',
            field=models.FileField(blank=True, null=True, upload_to='pedidos/', verbose_name='Documento de algun gremio'),
        ),
        migrations.CreateModel(
            name='UserAux2',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(blank=True, max_length=120, null=True)),
                ('nombre', models.CharField(blank=True, max_length=30, null=True)),
                ('apellido', models.CharField(blank=True, max_length=150, null=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('password', models.CharField(blank=True, max_length=120, null=True)),
                ('codigo', models.CharField(blank=True, max_length=6, null=True)),
                ('foto', models.ImageField(blank=True, null=True, upload_to='pedidos/', verbose_name='Foto')),
                ('upload', models.FileField(blank=True, null=True, upload_to='pedidos/', verbose_name='Documento de algun gremio')),
                ('bandera_foto', models.CharField(blank=True, max_length=120, null=True)),
                ('bandera_upload', models.CharField(blank=True, max_length=120, null=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
