# Generated by Django 2.2.24 on 2021-10-04 22:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0059_helprequest_2_historicalhelprequest_2'),
    ]

    operations = [
        migrations.AddField(
            model_name='reserva',
            name='producto',
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
    ]
