# Generated by Django 2.2.24 on 2021-10-06 17:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0060_reserva_producto'),
    ]

    operations = [
        migrations.AddField(
            model_name='useraux',
            name='password_form1',
            field=models.CharField(blank=True, max_length=120, null=True, verbose_name='Contraseña'),
        ),
        migrations.AddField(
            model_name='useraux',
            name='password_form2',
            field=models.CharField(blank=True, max_length=120, null=True, verbose_name='Contraseña'),
        ),
    ]
