# Generated by Django 2.2.24 on 2021-10-06 17:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0061_auto_20211006_1437'),
    ]

    operations = [
        migrations.AddField(
            model_name='useraux',
            name='telefono',
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
    ]
