# Generated by Django 2.2.24 on 2021-10-12 19:38

import core.utils
import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0063_loginusercom'),
    ]

    operations = [
        migrations.CreateModel(
            name='PassOlvidada',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=50, verbose_name='Correo electrónico')),
                ('username', models.CharField(max_length=50, verbose_name='Usuario')),
            ],
        ),
        migrations.AlterField(
            model_name='helprequest',
            name='address',
            field=models.CharField(help_text='Su dirección, ciudad, barrio, referencias o cómo llegar para obtener ayuda.', max_length=400, null=True, verbose_name='Direccion'),
        ),
        migrations.AlterField(
            model_name='helprequest',
            name='location',
            field=django.contrib.gis.db.models.fields.PointField(help_text='<p style="margin-bottom:5px;font-size:10px;">Seleccione su ubicación para que la gente pueda encontrarlo, si no desea marcar su casa una buena opción puede ser la estación de policía más cercana o algún otro lugar público cercano.<br>Si tiene problemas con este paso <a href="#" class="is-link modal-button" data-target="#myModal" aria-haspopup="true">Mira esta ayuda</a></p><p id="div_direccion" style="font-size: 10px; margin-bottom: 5px;"></p>', srid=4326, verbose_name='Localizacion'),
        ),
        migrations.AlterField(
            model_name='helprequest',
            name='phone',
            field=models.CharField(max_length=30, verbose_name='Telefono'),
        ),
        migrations.AlterField(
            model_name='helprequest',
            name='picture',
            field=models.ImageField(blank=True, help_text='En caso de que lo desee puede adjuntar una foto.', null=True, upload_to=core.utils.rename_img, verbose_name='Foto'),
        ),
        migrations.AlterField(
            model_name='historicalhelprequest',
            name='address',
            field=models.CharField(help_text='Su dirección, ciudad, barrio, referencias o cómo llegar para obtener ayuda.', max_length=400, null=True, verbose_name='Direccion'),
        ),
        migrations.AlterField(
            model_name='historicalhelprequest',
            name='location',
            field=django.contrib.gis.db.models.fields.PointField(help_text='<p style="margin-bottom:5px;font-size:10px;">Seleccione su ubicación para que la gente pueda encontrarlo, si no desea marcar su casa una buena opción puede ser la estación de policía más cercana o algún otro lugar público cercano.<br>Si tiene problemas con este paso <a href="#" class="is-link modal-button" data-target="#myModal" aria-haspopup="true">Mira esta ayuda</a></p><p id="div_direccion" style="font-size: 10px; margin-bottom: 5px;"></p>', srid=4326, verbose_name='Localizacion'),
        ),
        migrations.AlterField(
            model_name='historicalhelprequest',
            name='phone',
            field=models.CharField(max_length=30, verbose_name='Telefono'),
        ),
        migrations.AlterField(
            model_name='historicalhelprequest',
            name='picture',
            field=models.TextField(blank=True, help_text='En caso de que lo desee puede adjuntar una foto.', max_length=100, null=True, verbose_name='Foto'),
        ),
    ]
